name: Run tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.7']
        os: [ubuntu-latest, macOS-latest]
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - name: Run tests
        run: julia --project=@. test/runtests.jl
